post https://mun-super-palvelu-jee-jee.onrender.com/customers
content-type: application/json

{ "name": "Kalle" }

###

get https://mun-super-palvelu-jee-jee.onrender.com/customers

###

get http://127.0.0.1:8000/customers

###

post http://127.0.0.1:8000/customers
content-type: application/json

{ "name": "Kaldsdsdsle" }